// Core calculation logic for the Queue-it Max Outflow explainer.
//
// Model (from Little's Law):
//   L = lambda * W
//     L      = concurrent active users on the site
//     lambda = admission rate (users per minute) -> this is the Max Outflow
//     W      = average stay time / journey length (minutes)
//
// Sizing chain:
//   throughput capacity  --(per-user rate)-->  concurrent capacity (L)
//   concurrent capacity  --(x utilization)-->  target concurrency
//   target concurrency   --(/ W)----------->  recommended Max Outflow (users/min)

export type Metric = "concurrent" | "tps" | "rps" | "pageviews";
export type TimeBasis = "sec" | "min";

export interface CalcInput {
  metric: Metric;
  /** Capacity value expressed in the metric's unit. For "concurrent" this is the user count. */
  capacityValue: number;
  /** Time basis for page views (per second / per minute). TPS & RPS are always per second. */
  timeBasis: TimeBasis;
  /** Throughput generated by ONE active user, in the same unit/basis as capacityValue. */
  perUserRate: number;
  /** Average stay time / journey length W, in minutes. */
  stayMinutes: number;
  /** Target backend utilization, 0..1 (e.g. 0.8 = 80%). */
  utilization: number;
}

export interface CalcResult {
  /** L_max: concurrent active-user capacity. */
  concurrentCapacity: number;
  /** L_target = L_max * utilization: the concurrency you actually aim for. */
  targetConcurrency: number;
  /** Theoretical ceiling for Max Outflow = L_max / W (users/min). */
  theoreticalOutflow: number;
  /** Recommended Max Outflow = L_target / W (users/min). */
  recommendedOutflow: number;
  /** Recommended outflow expressed per second. */
  outflowPerSecond: number;
  /** Approx throughput at steady state, in the metric's unit (undefined for "concurrent"). */
  steadyStateThroughput?: number;
  /** Minute at which the first admitted cohort begins to leave (W + 1, rounded). */
  transitionMinute: number;
  /** Whether the inputs produce a usable result. */
  valid: boolean;
}

export interface TimelinePoint {
  minute: number;
  admitted: number;
  leaving: number;
  active: number;
  /** Active users as a fraction of full concurrent capacity (0..1). */
  capacityFraction: number;
}

const isPos = (n: number) => typeof n === "number" && isFinite(n) && n > 0;

export function calculate(input: CalcInput): CalcResult {
  const { metric, capacityValue, perUserRate, stayMinutes, utilization } = input;

  const empty: CalcResult = {
    concurrentCapacity: 0,
    targetConcurrency: 0,
    theoreticalOutflow: 0,
    recommendedOutflow: 0,
    outflowPerSecond: 0,
    transitionMinute: 0,
    valid: false,
  };

  if (!isPos(capacityValue) || !isPos(stayMinutes) || !isPos(utilization)) {
    return empty;
  }

  let concurrentCapacity: number;
  let steadyStateThroughput: number | undefined;

  if (metric === "concurrent") {
    concurrentCapacity = capacityValue;
  } else {
    if (!isPos(perUserRate)) return empty;
    // CU = Total throughput / throughput per active user
    concurrentCapacity = capacityValue / perUserRate;
  }

  const targetConcurrency = concurrentCapacity * utilization;
  const theoreticalOutflow = concurrentCapacity / stayMinutes;
  const recommendedOutflow = targetConcurrency / stayMinutes;

  if (metric !== "concurrent") {
    // At steady state, throughput ≈ target concurrency × per-user rate ≈ utilization × capacity.
    steadyStateThroughput = targetConcurrency * perUserRate;
  }

  return {
    concurrentCapacity,
    targetConcurrency,
    theoreticalOutflow,
    recommendedOutflow,
    outflowPerSecond: recommendedOutflow / 60,
    steadyStateThroughput,
    transitionMinute: Math.round(stayMinutes) + 1,
    valid: true,
  };
}

/**
 * Simulate active users minute-by-minute assuming the queue always has waiters,
 * so exactly `rate` users are admitted every minute starting at minute 1, and a
 * cohort admitted at minute m leaves at minute m + W.
 *
 * active(m) = rate * min(m, W)   (ramp until W, then flat plateau)
 */
export function buildTimeline(
  rate: number,
  stayMinutes: number,
  horizon: number
): TimelinePoint[] {
  const points: TimelinePoint[] = [];
  const W = stayMinutes;
  const plateau = rate * W; // steady-state active users at this rate

  const cumLeft = (m: number) => rate * Math.max(0, m - W);

  for (let m = 0; m <= horizon; m++) {
    const admitted = m === 0 ? 0 : rate;
    const active = rate * Math.min(m, W);
    const leaving = cumLeft(m) - cumLeft(m - 1);
    points.push({
      minute: m,
      admitted,
      leaving: m === 0 ? 0 : leaving,
      active,
      capacityFraction: plateau > 0 ? active / plateau : 0,
    });
  }
  return points;
}

/** A sensible number of minutes to display so the ramp-to-plateau transition is visible. */
export function timelineHorizon(stayMinutes: number): number {
  const w = Math.round(stayMinutes);
  return Math.min(Math.max(w * 2, w + 4, 12), 40);
}

/**
 * Per-user throughput (per second) estimated from browsing behavior:
 * a user performs one action every `thinkSeconds`, and each action triggers
 * `actionsPerClick` units of the metric (e.g. requests per page load).
 *   rate/sec = actionsPerClick / thinkSeconds
 */
export function perUserRateFromBehavior(
  actionsPerClick: number,
  thinkSeconds: number,
  basis: TimeBasis
): number {
  if (!isPos(actionsPerClick) || !isPos(thinkSeconds)) return 0;
  const perSecond = actionsPerClick / thinkSeconds;
  return basis === "min" ? perSecond * 60 : perSecond;
}
